name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTlkZDFlYWYtMzZhNi00N2ZmLTg0YzItMThhZGExZTJjZmViIiwidGVuYW50X2lkIjoiMGJhMWUxNTg4ZDc0YTNlNGM2MjM1NTI3YWE3NzIwYzgzMmE0OTk2NmIwNGMwOTE0OGQ3MDI5ODgzNWNiNDM5ZCIsImludGVybmFsX3NlY3JldCI6Ijg1NzBiNDQwLWJiMjEtNGM0OS1hZTcxLWFmMmIwOGRiZDViOCJ9.aSYu8b-jgNoRW1G3R__8zxfI81ak_D2_VaF2UmeYY6U"
JWT_SECRET="mysecret"
